version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      timezone: "Europe/Berlin"
    reviewers:
      - "alexandrevilain"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Europe/Berlin"
    reviewers:
      - "alexandrevilain"