changelog:
  categories:
    - title: ✨ Features
      labels:
        - '*'
      exclude:
        labels:
          - bugfix
          - documentation
          - dependencies
          - cleanup
    - title: 🐛 Bug fixes
      labels:
        - bugfix
    - title: 📖 Documentation
      labels:
        - documentation
    - title: 🔨 Dependencies
      labels:
        - dependencies
    - title: 🌱 Cleanup
      labels:
        - cleanup